/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Idhesive API
 * Idhesive API for intelligent policy management and enforcement platform
 * OpenAPI spec version: 0.0.0
 */
import type { TokenInfo } from './tokenInfo';
import type { User } from './user';

/**
 * Authentication response model
 */
export interface AuthResponse {
  /** Authentication token information */
  token: TokenInfo;
  /** User information */
  user: User;
}
