/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Idhesive API
 * Idhesive API for intelligent policy management and enforcement platform
 * OpenAPI spec version: 0.0.0
 */
import type { Organization } from './organization';
import type { User } from './user';

/**
 * Organization creation request
 */
export interface CreateOrganizationRequest {
  /** Organization details */
  organization: Organization;
  /** Initial owner user details */
  owner: User;
}
