/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Idhesive API
 * Idhesive API for intelligent policy management and enforcement platform
 * OpenAPI spec version: 0.0.0
 */

/**
 * Login request model
 */
export interface LoginRequest {
  /** User email */
  email: string;
  /** User password */
  password: string;
}
