/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Idhesive API
 * Idhesive API for intelligent policy management and enforcement platform
 * OpenAPI spec version: 0.0.0
 */
import type { Uuid } from './uuid';
import type { OrganizationStatus } from './organizationStatus';
import type { OrganizationBranding } from './organizationBranding';
import type { DateTime } from './dateTime';

/**
 * Organization model
 */
export interface Organization {
  /** Organization unique identifier */
  readonly id: Uuid;
  /** Organization name */
  name: string;
  /** Organization description */
  description?: string;
  /** Organization status */
  status: OrganizationStatus;
  /** Custom branding settings */
  branding?: OrganizationBranding;
  /** Creation timestamp */
  readonly createdAt: DateTime;
  /** Last update timestamp */
  readonly updatedAt: DateTime;
}
