/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Idhesive API
 * Idhesive API for intelligent policy management and enforcement platform
 * OpenAPI spec version: 0.0.0
 */

/**
 * Organization status
 */
export type OrganizationStatus =
  (typeof OrganizationStatus)[keyof typeof OrganizationStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrganizationStatus = {
  active: 'active',
  suspended: 'suspended',
  deactivated: 'deactivated'
} as const;
