/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Idhesive API
 * Idhesive API for intelligent policy management and enforcement platform
 * OpenAPI spec version: 0.0.0
 */

/**
 * User role within an organization
 */
export type OrganizationRole =
  (typeof OrganizationRole)[keyof typeof OrganizationRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OrganizationRole = {
  owner: 'owner',
  administrator: 'administrator',
  securityOfficer: 'securityOfficer',
  complianceManager: 'complianceManager',
  divisionAdmin: 'divisionAdmin',
  auditor: 'auditor',
  policyAdmin: 'policyAdmin',
  dataSourceAdmin: 'dataSourceAdmin',
  aiIntegrationManager: 'aiIntegrationManager',
  teamLead: 'teamLead',
  standardUser: 'standardUser',
  readOnlyUser: 'readOnlyUser'
} as const;
