/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Idhesive API
 * Idhesive API for intelligent policy management and enforcement platform
 * OpenAPI spec version: 0.0.0
 */
import type { Uuid } from './uuid';
import type { DateTime } from './dateTime';

/**
 * Project model
 */
export interface Project {
  /** Project unique identifier */
  readonly id: Uuid;
  /** Organization ID this Project belongs to */
  readonly organizationId: Uuid;
  /** Project name */
  name: string;
  /** Project description */
  description?: string;
  /** Creation timestamp */
  readonly createdAt: DateTime;
  /** Last update timestamp */
  readonly updatedAt: DateTime;
}
