/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Idhesive API
 * Idhesive API for intelligent policy management and enforcement platform
 * OpenAPI spec version: 0.0.0
 */
import type { Uuid } from './uuid';
import type { DateTime } from './dateTime';

/**
 * Team model
 */
export interface Team {
  /** Team unique identifier */
  readonly id: Uuid;
  /** Organization ID this team belongs to */
  readonly organizationId: Uuid;
  /** Team name */
  name: string;
  /** Team description */
  description?: string;
  /** Creation timestamp */
  readonly createdAt: DateTime;
  /** Last update timestamp */
  readonly updatedAt: DateTime;
}
