/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Idhesive API
 * Idhesive API for intelligent policy management and enforcement platform
 * OpenAPI spec version: 0.0.0
 */

/**
 * Team model
 */
export interface TeamUpdate {
  /** Team name */
  name?: string;
  /** Team description */
  description?: string;
}
