/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Idhesive API
 * Idhesive API for intelligent policy management and enforcement platform
 * OpenAPI spec version: 0.0.0
 */

/**
 * Authentication token information
 */
export interface TokenInfo {
  /** JWT access token */
  accessToken: string;
  /** JWT refresh token */
  refreshToken: string;
  /** Token type (usually 'bearer') */
  tokenType: string;
  /** Access token expiration time in seconds */
  expiresIn: number;
  /** Refresh token expiration time in seconds */
  refreshExpiresIn: number;
}
