/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Idhesive API
 * Idhesive API for intelligent policy management and enforcement platform
 * OpenAPI spec version: 0.0.0
 */
import type { OrganizationUpdate } from './organizationUpdate';

/**
 * Organization update request
 */
export interface UpdateOrganizationRequest {
  /** Organization details to update */
  organization?: OrganizationUpdate;
}
